<!-- 
RSS generated by JIRA (7.2.3#72005-sha1:73be91d2b96fc29303a7eb6820acf420e5d0ed65) at Tue Dec 06 12:08:09 EST 2016

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://issues.jboss.org/si/jira.issueviews:issue-xml/WFLY-88/WFLY-88.xml?field=key&amp;field=summary
-->
<rss version="0.92" >
<channel>
    <title>JBoss Issue Tracker</title>
    <link>https://issues.jboss.org</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-us</language>    <build-info>
        <version>7.2.3</version>
        <build-number>72005</build-number>
        <build-date>06-10-2016</build-date>
    </build-info>

<item>
            <title>[WFLY-88] Recovery not fully triggered when distributed transaction falls down at prepare phase of 2PC</title>
                <link>https://issues.jboss.org/browse/WFLY-88</link>
                <project id="12313721" key="WFLY">WildFly</project>
                    <description>&lt;p&gt;It looks like recovery process is not fully triggered on a distributed transaction when the transaction falls down at prepare phase of 2PC. In the new crash recovery tests over propagated transactions only one of two servers recovers from the crash, but the other keeps an unfinished tx in its tx log. &lt;/p&gt;

&lt;p&gt;It corresponds to prepareHaltClient and prepareHaltServer test methods of org.jboss.as.test.jbossts.crashrec.txpropagation.TxPropagationCrashRecoveryTestCase, see JBQA-2604 for general description of the new tests. The prepareHaltClient test crashes the server which initiated the transaction, while as the prepareHaltServer test crashes the second server.&lt;/p&gt;

&lt;p&gt;The tests are written against EAP6.x branch, so for reproducing this it is needed a built server from the 7.1 branch of AS7.&lt;/p&gt;

&lt;p&gt;Steps to reproduce.&lt;br/&gt;
1. git clone -b as7 git://git.app.eng.bos.redhat.com/jbossqe/eap-tests-transactions.git&lt;br/&gt;
2. cd eap-tests-transactions&lt;br/&gt;
3. git checkout tx_propag_crashrec_tests&lt;br/&gt;
4a. mvn clean verify -Dtest=TxPropagationCrashRecoveryTestCase#prepareHaltClient -Djboss.dist=&amp;lt;path to jboss-as-7.1.3.Final-SNAPSHOT&amp;gt;&lt;br/&gt;
or&lt;br/&gt;
4b. mvn clean verify -Dtest=TxPropagationCrashRecoveryTestCase#prepareHaltServer -Djboss.dist=&amp;lt;path to jboss-as-7.1.3.Final-SNAPSHOT&amp;gt;&lt;/p&gt;

&lt;p&gt;The logs of prepareHaltClient run attached to this jira.&lt;/p&gt;</description>
                <environment></environment>
        <key id="12473332">WFLY-88</key>
            <summary>Recovery not fully triggered when distributed transaction falls down at prepare phase of 2PC</summary>
                <type id="1" iconUrl="https://issues.jboss.org/secure/viewavatar?size=xsmall&amp;avatarId=13263&amp;avatarType=issuetype">Bug</type>
                                            <priority id="3" iconUrl="https://issues.jboss.org/images/icons/priorities/major.svg">Major</priority>
                        <status id="5" iconUrl="https://issues.jboss.org/images/icons/statuses/resolved.png" description="A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.">Resolved</status>
                    <statusCategory id="3" key="done" colorName="green"/>
                                    <resolution id="1">Done</resolution>
                                        <assignee username="jaikiran">jaikiran pai</assignee>
                                    <reporter username="istudens">Ivo Studensky</reporter>
                        <labels>
                    </labels>
                <created>Wed, 29 Aug 2012 10:01:30 -0400</created>
                <updated>Mon, 24 Feb 2014 17:52:59 -0500</updated>
                            <resolved>Tue, 23 Apr 2013 06:30:29 -0400</resolved>
                                                    <fixVersion>8.0.0.Alpha1</fixVersion>
                                    <component>EJB</component>
                    <component>Remoting</component>
                        <due></due>
                            <votes>0</votes>
                                    <watches>6</watches>
                                                                <comments>
                            <comment id="12714587" author="tomjenkinson" created="Wed, 29 Aug 2012 10:50:19 -0400"  >&lt;p&gt;Maybe I did something silly?&lt;/p&gt;

&lt;p&gt;mvn clean verify -Dtest=TxPropagationCrashRecoveryTestCase#prepareHaltClient -Djboss.dist=~/projects/jbossas/jboss-as/build/target/jboss-as-7.1.3.Final-SNAPSHOT/&lt;/p&gt;


&lt;p&gt;&amp;lt;SNIP/&amp;gt;&lt;br/&gt;
build-jbossts:&lt;br/&gt;
     &lt;span class=&quot;error&quot;&gt;&amp;#91;echo&amp;#93;&lt;/span&gt; Building config jbossas-jbossts&lt;br/&gt;
     &lt;span class=&quot;error&quot;&gt;&amp;#91;copy&amp;#93;&lt;/span&gt; Copying 4 files to /home/tom/projects/eap-tests-transactions/integration/jbossts/target/jbossas-jbossts&lt;br/&gt;
     &lt;span class=&quot;error&quot;&gt;&amp;#91;echo&amp;#93;&lt;/span&gt;     ===  Changing IP addresses for config jbossas-jbossts ===  &lt;br/&gt;
     &lt;span class=&quot;error&quot;&gt;&amp;#91;echo&amp;#93;&lt;/span&gt;    node: 127.0.0.1&lt;br/&gt;
     &lt;span class=&quot;error&quot;&gt;&amp;#91;echo&amp;#93;&lt;/span&gt;    ant.mcast: @&lt;/p&gt;
{ant.mcast}
&lt;p&gt;&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; ------------------------------------------------------------------------&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; Reactor Summary:&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; &lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; JBoss EAP Server Test Suite: Aggregator ........... SUCCESS &lt;span class=&quot;error&quot;&gt;&amp;#91;11.732s&amp;#93;&lt;/span&gt;&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; JBoss EAP Server Test Suite: Integration .......... SUCCESS &lt;span class=&quot;error&quot;&gt;&amp;#91;0.856s&amp;#93;&lt;/span&gt;&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; JBoss EAP Server Test Suite: Integration - JBossTS tests  FAILURE &lt;span class=&quot;error&quot;&gt;&amp;#91;5.316s&amp;#93;&lt;/span&gt;&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; ------------------------------------------------------------------------&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; BUILD FAILURE&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; ------------------------------------------------------------------------&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; Total time: 18.853s&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; Finished at: Wed Aug 29 15:49:06 BST 2012&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; Final Memory: 42M/484M&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;INFO&amp;#93;&lt;/span&gt; ------------------------------------------------------------------------&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;ERROR&amp;#93;&lt;/span&gt; Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (build-jbossts.server) on project jboss-eap-ts-integ-jbossts: An Ant BuildException has occured: The following error occurred while executing this line:&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;ERROR&amp;#93;&lt;/span&gt; /home/tom/projects/eap-tests-transactions/integration/src/test/scripts/jbossts-build.xml:17: The following error occurred while executing this line:&lt;br/&gt;
&lt;span class=&quot;error&quot;&gt;&amp;#91;ERROR&amp;#93;&lt;/span&gt; /home/tom/projects/eap-tests-transactions/integration/src/test/scripts/common-targets.xml:82: no resources specified&lt;br/&gt;
&amp;lt;SNIP/&amp;gt;&lt;/p&gt;</comment>
                            <comment id="12714802" author="istudens" created="Thu, 30 Aug 2012 05:19:13 -0400"  >&lt;p&gt;Mmm, that&apos;s weird. I&apos;ve just give it a try from a clean clone from git and did not hit such issue.&lt;br/&gt;
Anyway, Tom, I am looking into your quickstarts now. I will get back to you if I do not find any diffs.&lt;/p&gt;</comment>
                            <comment id="12715092" author="tomjenkinson" created="Fri, 31 Aug 2012 06:24:48 -0400"  >&lt;p&gt;D&apos;oh, it was because I had a tilde instead of /home/tom, test is running now&lt;/p&gt;</comment>
                            <comment id="12715099" author="istudens" created="Fri, 31 Aug 2012 07:12:25 -0400"  >&lt;p&gt;This issue affects JTA distributed transactions (via EJB Remoting).&lt;/p&gt;</comment>
                            <comment id="12726323" author="tomjenkinson" created="Mon, 15 Oct 2012 03:23:25 -0400"  >&lt;p&gt;Doesn&apos;t affect JTS&lt;/p&gt;</comment>
                            <comment id="12736900" author="tomjenkinson" created="Mon, 26 Nov 2012 06:30:24 -0500"  >&lt;p&gt;This looks like server 1 is not configured to connect to server 2 to recover the transactions. &lt;/p&gt;

&lt;p&gt;To the new assignee, this is not a JBoss Transactions issue, it is a small issue in the integration code where you are meant to configure a XARecoveryModule that can connect to known servers to see if they have any transactions that were started at this server.&lt;/p&gt;

&lt;p&gt;This is a &quot;distributed JTA&quot; issue, not JTA/JTS.&lt;/p&gt;</comment>
                            <comment id="12736902" author="tomjenkinson" created="Mon, 26 Nov 2012 06:35:23 -0500"  >&lt;p&gt;The impact is that recovery will never be performed on remote nodes when using &quot;Distributed JTA&quot;&lt;/p&gt;</comment>
                            <comment id="12737656" author="jaikiran" created="Wed, 28 Nov 2012 06:15:58 -0500"  >&lt;p&gt;Thanks Tom, I&apos;ll look into what needs to be done.&lt;/p&gt;</comment>
                            <comment id="12767615" author="jira-bugzilla-migration" created="Tue, 16 Apr 2013 11:25:33 -0400"  >&lt;p&gt;Jaikiran Pai &amp;lt;jpai@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;The QA team has certain testcases (in an internal git repo) which exposed non-functioning of remote EJB transaction recovery functionality:&lt;/p&gt;

&lt;p&gt;&lt;a href=&quot;https://issues.jboss.org/browse/AS7-6029&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://issues.jboss.org/browse/AS7-6029&lt;/a&gt;&lt;br/&gt;
&lt;a href=&quot;https://issues.jboss.org/browse/AS7-6030&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://issues.jboss.org/browse/AS7-6030&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Investigating these failures led to enhancements in EJBCLIENT project and bug fix in Narayana project. With these fixes/patches, the tests are now passing. The Narayana project is going to be released tomorrow (Tom is waiting for one other fix to be completed before doing the release, which he expects to be done by tomorrow). Once that bug fix is released tomorrow, I&apos;ll be sending a PR to EAP repo to bring in the new versions for Narayana and EJB client projects and do necessary upgrades to integrate that new version.&lt;/p&gt;</comment>
                            <comment id="12768774" author="jaikiran" created="Fri, 19 Apr 2013 07:23:33 -0400"  >&lt;p&gt;Pull request sent&lt;/p&gt;</comment>
                            <comment id="12769703" author="jira-bugzilla-migration" created="Tue, 23 Apr 2013 19:51:48 -0400"  >&lt;p&gt;Brian Stansberry &amp;lt;brian.stansberry@redhat.com&amp;gt; changed the Status of &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt; from NEW to POST&lt;/p&gt;</comment>
                            <comment id="12770260" author="jira-bugzilla-migration" created="Thu, 25 Apr 2013 17:20:01 -0400"  >&lt;p&gt;Paul Gier &amp;lt;pgier@redhat.com&amp;gt; changed the Status of &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt; from POST to MODIFIED&lt;/p&gt;</comment>
                            <comment id="12771276" author="jira-bugzilla-migration" created="Tue, 30 Apr 2013 20:50:46 -0400"  >&lt;p&gt;Paul Gier &amp;lt;pgier@redhat.com&amp;gt; changed the Status of &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt; from MODIFIED to ON_QA&lt;/p&gt;</comment>
                            <comment id="12772267" author="jira-bugzilla-migration" created="Mon, 6 May 2013 05:46:20 -0400"  >&lt;p&gt;Jaikiran Pai &amp;lt;jpai@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;FYI - I believe this needs to be tested against ER7 instead of ER6 since there was a change that was required in EJB client project (as well as server side from what I remember) to fix one of the recovery tests.&lt;/p&gt;</comment>
                            <comment id="12773872" author="jira-bugzilla-migration" created="Mon, 13 May 2013 12:11:23 -0400"  >&lt;p&gt;Ondrej Chaloupka &amp;lt;ochaloup@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Hi,&lt;/p&gt;

&lt;p&gt;I&apos;ve retested the issue on ER8 and the test is still failing. The problematic test is commitHaltRevServer where commit after recovery is supposed and rollback is provided.&lt;/p&gt;

&lt;p&gt;I&apos;m using your test fix.&lt;/p&gt;

&lt;p&gt;I was doing several changes to be sure but I&apos;m still getting the same fail result. &lt;/p&gt;

&lt;p&gt;Reproducing should be possible to do in the way similar to:&lt;br/&gt;
git clone git://git.app.eng.bos.redhat.com/jbossqe/eap-tests-transactions.git&lt;br/&gt;
wget &lt;a href=&quot;http://download.devel.redhat.com/devel/candidates/JBEAP/JBEAP-6.1.0-ER8/jboss-eap-6.1.0.ER8.zip&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://download.devel.redhat.com/devel/candidates/JBEAP/JBEAP-6.1.0-ER8/jboss-eap-6.1.0.ER8.zip&lt;/a&gt;&lt;br/&gt;
unzip jboss-eap-6.1.0.ER8.zip&lt;br/&gt;
export JBOSS_HOME=$PWD/jboss-eap-6.1&lt;br/&gt;
cd eap-tests-transactions/integration/jbossts&lt;br/&gt;
mvn clean verify -Djboss.dist=$JBOSS_HOME -Dtest=TxPropagationCrashRecoveryTestCase#commitHaltRevServer -Djbossts.noJTS &lt;/p&gt;

&lt;p&gt;Would you be so kind and check this?&lt;/p&gt;</comment>
                            <comment id="12773973" author="jira-bugzilla-migration" created="Tue, 14 May 2013 00:13:27 -0400"  >&lt;p&gt;Jaikiran Pai &amp;lt;jpai@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Ondra, have you applied the patch(es) to the test setup that I sent across the other day?&lt;/p&gt;</comment>
                            <comment id="12773992" author="jira-bugzilla-migration" created="Tue, 14 May 2013 04:14:51 -0400"  >&lt;p&gt;Ondrej Chaloupka &amp;lt;ochaloup@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Yeap, I&apos;ve applied the patch. There is added callDoNothing call.&lt;br/&gt;
You can check it in the git repo:&lt;br/&gt;
&lt;a href=&quot;http://git.app.eng.bos.redhat.com/?p=jbossqe/eap-tests-transactions.git;a=blob;f=integration/jbossts/src/test/java/org/jboss/as/test/jbossts/crashrec/txpropagation/TxPropagationCrashRecoveryTestBase.java;h=0ba2e8392b9d54df9e24742c2ebaab7d79f14f82;hb=911910ff12a9f30a5fdef562427dda447f2b6886#l458&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;http://git.app.eng.bos.redhat.com/?p=jbossqe/eap-tests-transactions.git;a=blob;f=integration/jbossts/src/test/java/org/jboss/as/test/jbossts/crashrec/txpropagation/TxPropagationCrashRecoveryTestBase.java;h=0ba2e8392b9d54df9e24742c2ebaab7d79f14f82;hb=911910ff12a9f30a5fdef562427dda447f2b6886#l458&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;There is a warn message which seems to be related to the issue. &lt;br/&gt;
14:52:03,960 WARN  &lt;span class=&quot;error&quot;&gt;&amp;#91;com.arjuna.ats.jta&amp;#93;&lt;/span&gt; (EJB default - 4) ARJUNA016038: No XAResource to recover &amp;lt; formatId=131077, gtrid_length=29, bqual_length=36, tx_uid=0:ffff7f000001:-72f4ed54:5190e173:11, node_name=1, branch_uid=0:ffff7f000001:27821ad6:5190e17a:1a, subordinatenodename=2, eis_name=java:/JmsXA &amp;gt;&lt;/p&gt;

&lt;p&gt;And the &quot;client&quot; server is still showing the exception message.&lt;br/&gt;
14:50:43,137 WARN  &lt;span class=&quot;error&quot;&gt;&amp;#91;com.arjuna.ats.jta&amp;#93;&lt;/span&gt; (Periodic Recovery) ARJUNA016036: commit on &amp;lt; formatId=131077, gtrid_length=29, bqual_length=36, tx_uid=0:ffff7f000001:-72f4ed54:5190e173:11, node_name=1, branch_uid=0:ffff7f000001:-72f4ed54:5190e173:1e, subordinatenodename=null, eis_name=unknown eis name &amp;gt; (RecoveryOnlySerializedEJBXAResource&lt;/p&gt;
{ejbReceiverNodeName=&apos;jbossts2&apos;}
&lt;p&gt;) failed with exception $XAException.XA_RETRY: javax.transaction.xa.XAException&lt;br/&gt;
 at_org.jboss.ejb.client.RecoveryOnlySerializedEJBXAResource.commit(RecoveryOnlySerializedEJBXAResource.java:51)&lt;br/&gt;
 at_com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelCommit(XAResourceRecord.java:451) &lt;span class=&quot;error&quot;&gt;&amp;#91;jbossjts-jacorb-4.17.4.Final-redhat-2.jar:4.17.4.Final-redhat-2&amp;#93;&lt;/span&gt;&lt;br/&gt;
 at_com.arjuna.ats.arjuna.coordinator.BasicAction.doCommit(BasicAction.java:2732) &lt;span class=&quot;error&quot;&gt;&amp;#91;jbossjts-jacorb-4.17.4.Final-redhat-2.jar:4.17.4.Final-redhat-2&amp;#93;&lt;/span&gt;&lt;br/&gt;
 at_com.arjuna.ats.arjuna.coordinator.BasicAction.doCommit(BasicAction.java:2648) &lt;span class=&quot;error&quot;&gt;&amp;#91;jbossjts-jacorb-4.17.4.Final-redhat-2.jar:4.17.4.Final-redhat-2&amp;#93;&lt;/span&gt;&lt;br/&gt;
 at_com.arjuna.ats.arjuna.coordinator.BasicAction.phase2Commit(BasicAction.java:1813) &lt;span class=&quot;error&quot;&gt;&amp;#91;jbossjts-jacorb-4.17.4.Final-redhat-2.jar:4.17.4.Final-redhat-2&amp;#93;&lt;/span&gt;&lt;br/&gt;
 at_com.arjuna.ats.arjuna.recovery.RecoverAtomicAction.replayPhase2(RecoverAtomicAction.java:71) &lt;span class=&quot;error&quot;&gt;&amp;#91;jbossjts-jacorb-4.17.4.Final-redhat-2.jar:4.17.4.Final-redhat-2&amp;#93;&lt;/span&gt;&lt;br/&gt;
 at_com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule.doRecoverTransaction(AtomicActionRecoveryModule.java:152) &lt;span class=&quot;error&quot;&gt;&amp;#91;jbossjts-jacorb-4.17.4.Final-redhat-2.jar:4.17.4.Final-redhat-2&amp;#93;&lt;/span&gt;&lt;br/&gt;
 at_com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule.processTransactionsStatus(AtomicActionRecoveryModule.java:251) &lt;span class=&quot;error&quot;&gt;&amp;#91;jbossjts-jacorb-4.17.4.Final-redhat-2.jar:4.17.4.Final-redhat-2&amp;#93;&lt;/span&gt;&lt;br/&gt;
 at_com.arjuna.ats.internal.arjuna.recovery.AtomicActionRecoveryModule.periodicWorkSecondPass(AtomicActionRecoveryModule.java:109) &lt;span class=&quot;error&quot;&gt;&amp;#91;jbossjts-jacorb-4.17.4.Final-redhat-2.jar:4.17.4.Final-redhat-2&amp;#93;&lt;/span&gt;&lt;br/&gt;
 at_com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.doWorkInternal(PeriodicRecovery.java:789) &lt;span class=&quot;error&quot;&gt;&amp;#91;jbossjts-jacorb-4.17.4.Final-redhat-2.jar:4.17.4.Final-redhat-2&amp;#93;&lt;/span&gt;&lt;br/&gt;
 at_com.arjuna.ats.internal.arjuna.recovery.PeriodicRecovery.run(PeriodicRecovery.java:371) &lt;span class=&quot;error&quot;&gt;&amp;#91;jbossjts-jacorb-4.17.4.Final-redhat-2.jar:4.17.4.Final-redhat-2&amp;#93;&lt;/span&gt; &lt;/p&gt;


&lt;p&gt;But...&lt;br/&gt;
Now I tried to put the callDoNothing immediately after the server reboot (line 481) the recovery started to work. But there is sti.l the warning message on the &quot;client&quot; server.&lt;br/&gt;
Just I wonder whether this is how it should work. Without immediate remote call the recovery fails...?&lt;/p&gt;</comment>
                            <comment id="12773994" author="jaikiran" created="Tue, 14 May 2013 04:27:57 -0400"  >&lt;blockquote&gt;&lt;p&gt; And the &quot;client&quot; server is still showing the exception message.&lt;br/&gt;
14:50:43,137 WARN &lt;span class=&quot;error&quot;&gt;&amp;#91;com.arjuna.ats.jta&amp;#93;&lt;/span&gt; (Periodic Recovery) ARJUNA016036: commit on &amp;lt; formatId=131077, gtrid_length=29, bqual_length=36, tx_uid=0:ffff7f000001:-72f4ed54:5190e173:11, node_name=1, branch_uid=0:ffff7f000001:-72f4ed54:5190e173:1e, subordinatenodename=null, eis_name=unknown eis name &amp;gt; (RecoveryOnlySerializedEJBXAResource&lt;/p&gt;
&lt;div class=&quot;error&quot;&gt;&lt;span class=&quot;error&quot;&gt;Unknown macro: {ejbReceiverNodeName=&amp;#39;jbossts2&amp;#39;}&lt;/span&gt; &lt;/div&gt;

&lt;p&gt;) failed with exception $XAException.XA_RETRY: javax.transaction.xa.XAException&lt;/p&gt;&lt;/blockquote&gt;
&lt;p&gt;That is intentional. Notice the XA_RETRY. The EJB client resource recovery throws this XA_RETRY exception if it doesn&apos;t yet have any connected servers to communicate to. This lets the Recovery Manager service know that the recovery of this XAResource has to be retried. Once the client-&amp;gt;server communication is established (for example, via the callDoNothing()) a subsequent recovery attempt will pass.&lt;/p&gt;</comment>
                            <comment id="12773999" author="jira-bugzilla-migration" created="Tue, 14 May 2013 04:36:13 -0400"  >&lt;p&gt;Ondrej Chaloupka &amp;lt;ochaloup@redhat.com&amp;gt; changed the Status of &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt; from ON_QA to VERIFIED&lt;/p&gt;</comment>
                            <comment id="12774000" author="jira-bugzilla-migration" created="Tue, 14 May 2013 04:36:13 -0400"  >&lt;p&gt;Ondrej Chaloupka &amp;lt;ochaloup@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Reaction from Jaikiran (see jira &lt;a href=&quot;https://issues.jboss.org/browse/WFLY-88&quot; title=&quot;Recovery not fully triggered when distributed transaction falls down at prepare phase of 2PC&quot; class=&quot;issue-link&quot; data-issue-key=&quot;WFLY-88&quot;&gt;&lt;del&gt;WFLY-88&lt;/del&gt;&lt;/a&gt;):&lt;br/&gt;
That is intentional. Notice the XA_RETRY. The EJB client resource recovery throws this XA_RETRY exception if it doesn&apos;t yet have any connected servers to communicate to. This lets the Recovery Manager service know that the recovery of this XAResource has to be retried. Once the client-&amp;gt;server communication is established (for example, via the callDoNothing()) a subsequent recovery attempt will pass.&lt;/p&gt;

&lt;p&gt;Then I assume that this issue is verified.&lt;/p&gt;</comment>
                            <comment id="12774001" author="ochaloup" created="Tue, 14 May 2013 04:36:40 -0400"  >&lt;p&gt;jaikiran: OK, I see.&lt;br/&gt;
Thanks.&lt;/p&gt;</comment>
                            <comment id="12774004" author="jira-bugzilla-migration" created="Tue, 14 May 2013 04:51:26 -0400"  >&lt;p&gt;Jaikiran Pai &amp;lt;jpai@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;&amp;gt;&amp;gt; Then I assume that this issue is verified.&lt;/p&gt;

&lt;p&gt;Ondra, give me a few more minutes. Although, that WARN is fine, what you currently had in the testcase should have worked. You shouldn&apos;t have had to move that callDoNothing() call from where it was earlier. I am taking a look as to why it was failing in that scenario.&lt;/p&gt;</comment>
                            <comment id="12774005" author="jira-bugzilla-migration" created="Tue, 14 May 2013 04:51:27 -0400"  >&lt;p&gt;Jaikiran Pai &amp;lt;jpai@redhat.com&amp;gt; changed the Status of &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt; from VERIFIED to ON_QA&lt;/p&gt;</comment>
                            <comment id="12774103" author="jira-bugzilla-migration" created="Tue, 14 May 2013 08:44:29 -0400"  >&lt;p&gt;Jaikiran Pai &amp;lt;jpai@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;The test is failing after a fix we did for the Xid decoding issue &lt;a href=&quot;https://github.com/jbossas/jboss-ejb-client/commit/6401f45e45a36a4c9e19a755d0da281d15107ba1&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://github.com/jbossas/jboss-ejb-client/commit/6401f45e45a36a4c9e19a755d0da281d15107ba1&lt;/a&gt;. The fix looks right to me so I&apos;ll have to dig into why this fails the way it does with HornetQ XA resource handling no longer identifying its XAResource. I think I know why moving the callDoNothing &quot;solves&quot; this, but that&apos;s a workaround. &lt;/p&gt;

&lt;p&gt;So to summarize, we have a specific case where the recovery can potentially fail. I&apos;ll update this bugzilla once I understand what&apos;s going on.&lt;/p&gt;</comment>
                            <comment id="12774494" author="jira-bugzilla-migration" created="Wed, 15 May 2013 10:29:19 -0400"  >&lt;p&gt;Ondrej Chaloupka &amp;lt;ochaloup@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;I&apos;m moving this to MODIFIED because Jaikiran will be checking it.&lt;/p&gt;

&lt;p&gt;From QA point of view this is not a blocker for the release. The functionality for crash recovery over ejb remoting was added and there is just one specific case which fails.&lt;br/&gt;
It&apos;s supposed that customers will be using (as it was so far) JTS which works fine.&lt;/p&gt;</comment>
                            <comment id="12774495" author="jira-bugzilla-migration" created="Wed, 15 May 2013 10:29:19 -0400"  >&lt;p&gt;Ondrej Chaloupka &amp;lt;ochaloup@redhat.com&amp;gt; changed the Status of &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt; from ON_QA to MODIFIED&lt;/p&gt;</comment>
                            <comment id="12797288" author="jira-bugzilla-migration" created="Fri, 16 Aug 2013 07:47:15 -0400"  >&lt;p&gt;Ondrej Chaloupka &amp;lt;ochaloup@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Hi Jaikiran,&lt;/p&gt;

&lt;p&gt;please, could you give me info what is status of this bug? Is it already fixed in 6.1.1? &lt;br/&gt;
In case that this issue could be verified, please, change the status of the bz to ON_QA for me being able to verified it.&lt;/p&gt;

&lt;p&gt;Thank you&lt;br/&gt;
Ondra&lt;/p&gt;</comment>
                            <comment id="12799926" author="jira-bugzilla-migration" created="Wed, 28 Aug 2013 12:39:13 -0400"  >&lt;p&gt;Rostislav Svoboda &amp;lt;rsvoboda@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Jaikiran, do you have results ?&lt;/p&gt;</comment>
                            <comment id="12799931" author="jira-bugzilla-migration" created="Wed, 28 Aug 2013 12:56:35 -0400"  >&lt;p&gt;Jaikiran Pai &amp;lt;jpai@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Hi Rostislav,&lt;/p&gt;

&lt;p&gt;I do have the results and one specific test is failing out of a bunch of tests. I see what&apos;s going on but I don&apos;t yet know why. Progress has been a bit slow because the tests are long running to reproduce, investigate and retry again. So far, I haven&apos;t figured out the fix or an area/project to fix this. So I don&apos;t really have any real update yet, but am looking into it.&lt;/p&gt;</comment>
                            <comment id="12800045" author="jira-bugzilla-migration" created="Wed, 28 Aug 2013 23:28:52 -0400"  >&lt;p&gt;Scott Mumford &amp;lt;smumford@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Marking for exclusion from the 6.1.1 Release Notes document as an entry for this bug could not be completed or verified in time.&lt;/p&gt;</comment>
                            <comment id="12800253" author="jira-bugzilla-migration" created="Thu, 29 Aug 2013 09:46:18 -0400"  >&lt;p&gt;Rostislav Svoboda &amp;lt;rsvoboda@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Jaikiran, thank you for update.&lt;/p&gt;</comment>
                            <comment id="12824776" author="jira-bugzilla-migration" created="Thu, 24 Oct 2013 14:28:48 -0400"  >&lt;p&gt;Dimitris Andreadis &amp;lt;dandread@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Assigning jpai@redhat.com EJB issues to david.lloyd@redhat.com. Please re-assign to Cheng or others as needed.&lt;/p&gt;</comment>
                            <comment id="12825011" author="jira-bugzilla-migration" created="Fri, 25 Oct 2013 09:27:33 -0400"  >&lt;p&gt;David M. Lloyd &amp;lt;david.lloyd@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Per agreement with Ondrej, I&apos;m marking this as &quot;not a blocker&quot;.&lt;/p&gt;</comment>
                            <comment id="12825016" author="jira-bugzilla-migration" created="Fri, 25 Oct 2013 09:36:19 -0400"  >&lt;p&gt;Ondrej Chaloupka &amp;lt;ochaloup@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Agreed that this is not a blocker. Customers will use JTS transactions for distributed cases as it&apos;s supported way.&lt;/p&gt;

&lt;p&gt;The JTA distributed transactions are not ready till this will be validated and fixed.&lt;/p&gt;</comment>
                            <comment id="12825027" author="jira-bugzilla-migration" created="Fri, 25 Oct 2013 09:48:13 -0400"  >&lt;p&gt;mark yarborough &amp;lt;myarboro@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Triage: QE and Dev agree not a blocker for 6.2.&lt;/p&gt;</comment>
                            <comment id="12825971" author="jira-bugzilla-migration" created="Wed, 30 Oct 2013 17:43:58 -0400"  >&lt;p&gt;Paul Gier &amp;lt;pgier@redhat.com&amp;gt; changed the Status of &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt; from MODIFIED to ON_QA&lt;/p&gt;</comment>
                            <comment id="12827441" author="jira-bugzilla-migration" created="Fri, 1 Nov 2013 09:09:05 -0400"  >&lt;p&gt;Ondrej Chaloupka &amp;lt;ochaloup@redhat.com&amp;gt; changed the Status of &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt; from ON_QA to ASSIGNED&lt;/p&gt;</comment>
                            <comment id="12827442" author="jira-bugzilla-migration" created="Fri, 1 Nov 2013 09:09:06 -0400"  >&lt;p&gt;Ondrej Chaloupka &amp;lt;ochaloup@redhat.com&amp;gt; made a comment on &lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;bug 952746&lt;/a&gt;&lt;/p&gt;

&lt;p&gt;Hi David,&lt;/p&gt;

&lt;p&gt;I&apos;ve checked the current state of the issue (as it&apos;s longer time that I&apos;ve been checking it) and I can say that there is still the problem in the waking up the ejb remote connection when the remote server (remote server which is called from client server - via outbound connection from client server) crashes and then comes up again. Then the client sever (it started the tx) does not know nothing about the remote server is up and that the recovery can be done.&lt;/p&gt;

&lt;p&gt;This happen just for the distributed JTA transactions. The JTS transactions manage the distributed communication between nodes and the recovery starts without problem.&lt;/p&gt;

&lt;p&gt;The workaround for the recovery is to call a remote method from the client server to the remote server after the remote server comes back to life. Then the crash recovery will start.&lt;/p&gt;

&lt;p&gt;The test scenario when this problem occurs look:&lt;/p&gt;
&lt;ul class=&quot;alternate&quot; type=&quot;square&quot;&gt;
	&lt;li&gt;transaction is started on the client server&lt;/li&gt;
	&lt;li&gt;the client server does call via outbound connection to the remote server (tx context is propagated to remote server)&lt;/li&gt;
	&lt;li&gt;the remote server sends a message to a queue (simulation of some action done during the transaction)&lt;/li&gt;
	&lt;li&gt;finishing the remote call and the bean method&lt;/li&gt;
	&lt;li&gt;the transaction started 2PC. The prepare phase is done and the commit phase is started. The remote server crashes at the entry to the commit method&lt;/li&gt;
	&lt;li&gt;client server is still alive&lt;/li&gt;
	&lt;li&gt;remote server comes to life&lt;/li&gt;
	&lt;li&gt;the crash recovery should proceed the commit as all the participant agreed on it&lt;/li&gt;
&lt;/ul&gt;


&lt;p&gt;I would put here the explanation from Jaikiran:&lt;br/&gt;
When a connection breaks down between the server and the client, specifically when the client goes down and comes back up again, then the server and the client will not auto communicate with each other. &lt;br/&gt;
In other words, the server will have no knowledge (in EJB resource sense) that the client has come back up again. That effectively means that the EJB tx recovery process will have no clue of the EJB nodes to communicate with.&lt;br/&gt;
To deal with that, there should be some communication from the client (which is now up) to the server to reestablish that connection. &lt;br/&gt;
In a real application, it would be the first invocation from the client to the server. &lt;/p&gt;


&lt;p&gt;I&apos;ve checked that the call from the client server to remote one really establishes the connection and recovery starts.&lt;br/&gt;
B the next call from the client to server could take some time and meanwhile the transaction could be rollbacked because of the timeout.&lt;/p&gt;

&lt;p&gt;What do you think about this?&lt;br/&gt;
I think that current behavior is not correct. We agreed on it with Jaikiran before as well but he haven&apos;t got a time to fix it (&lt;a href=&quot;https://bugzilla.redhat.com/show_bug.cgi?id=952746#c15&quot; class=&quot;external-link&quot; rel=&quot;nofollow&quot;&gt;https://bugzilla.redhat.com/show_bug.cgi?id=952746#c15&lt;/a&gt;).&lt;/p&gt;

&lt;p&gt;Thanks&lt;br/&gt;
Ondra&lt;/p&gt;</comment>
                    </comments>
                <issuelinks>
                            <issuelinktype id="10012">
                    <name>Dependency</name>
                                            <outwardlinks description="is blocked by">
                                        <issuelink>
            <issuekey id="12488490">EJBCLIENT-72</issuekey>
        </issuelink>
                            </outwardlinks>
                                                                <inwardlinks description="blocks">
                                                        </inwardlinks>
                                    </issuelinktype>
                            <issuelinktype id="12310001">
                    <name>Related</name>
                                                                <inwardlinks description="is related to">
                                        <issuelink>
            <issuekey id="12473334">WFLY-107</issuekey>
        </issuelink>
                            </inwardlinks>
                                    </issuelinktype>
                    </issuelinks>
                <attachments>
                            <attachment id="12356481" name="logs_prepareHaltClient.tgz" size="46907" author="istudens" created="Wed, 29 Aug 2012 10:03:15 -0400"/>
                    </attachments>
                <subtasks>
                    </subtasks>
                <customfields>
                                                                            <customfield id="customfield_12310440" key="org.jboss.labs.jira.plugin.jboss-custom-field-types-plugin:multiurl">
                        <customfieldname>Bugzilla References</customfieldname>
                        <customfieldvalues>
                            https://bugzilla.redhat.com/show_bug.cgi?id=952746
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <customfield id="customfield_12310220" key="org.jboss.labs.jira.plugin.jboss-custom-field-types-plugin:multiurl">
                        <customfieldname>Git Pull Request</customfieldname>
                        <customfieldvalues>
                            https://github.com/jbossas/jboss-as/pull/4408
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                    <customfield id="customfield_12310641" key="com.atlassian.jira.toolkit:attachments">
                        <customfieldname>Number of attachments</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>1.0</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_12310640" key="com.atlassian.jira.toolkit:comments">
                        <customfieldname>Number of comments</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>38.0</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                            <customfield id="customfield_12311940" key="com.pyxis.greenhopper.jira:gh-lexo-rank">
                        <customfieldname>Rank</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>1|hz5dnr:</customfieldvalue>

                        </customfieldvalues>
                    </customfield>
                                                                <customfield id="customfield_12310840" key="com.pyxis.greenhopper.jira:gh-global-rank">
                        <customfieldname>Rank (Obsolete)</customfieldname>
                        <customfieldvalues>
                            <customfieldvalue>91781</customfieldvalue>
                        </customfieldvalues>
                    </customfield>
                                                                                                                                                                                                                                                                                                                                                                                    </customfields>
    </item>
</channel>
</rss>