Multithreaded step re-processing chunk without skip or retry limit.
I sort of understand this, and it's quite an amusing little bug (if rather irritating).  
I doubt if it critical at all, since the outcome of the step is still failure.
In a multi-threaded step we can only check for the failure one thread at a time, and by the time we have checked it, the failed chunk can have gone back in the queue for processing.  
Oddly, though, even with a single background thread it still fails the same way, so maybe we can actually fix this at least for some special cases.